
import { Job, MowEstimate } from '../types';

export const mockJobs: Job[] = [
  {
    id: 'JOB-0001',
    clientName: 'Charlie Fackler',
    phone: '717-555-0456',
    email: '',
    address: '45 Oak Ridge Dr',
    cityArea: 'Dover',
    description: 'Backyard paver patio',
    jobType: 'Paver Patio',
    status: 'Scheduled',
    priority: 'High',
    leadSource: 'Facebook',
    lastContactDate: '',
    nextAction: 'order patio pavers',
    nextActionDate: '2025-12-12',
    scheduledDate: '2025-12-15',
    timeWindow: '8:00 AM - 4:00 PM',
    crewLead: 'Chad',
    crewSize: 3,
    estHours: 16,
    estRevenue: 3000,
    estCost: 1800,
    estProfit: 1200,
    estMargin: 40.0,
    paymentStatus: 'Unpaid',
    notes: '',
    actualLaborHours: 14,
    actualLaborCost: 0,
    actualMaterialCost: 0,
    actualProfit: 1200,
    jobCostingVariance: 0,
    materialsList: 'Pavers, Edge restraint, Sand',
    equipmentNeeded: 'Skid steer, Plate compactor',
    siteAccessNotes: 'Side gate access',
    rejectionReason: '',
    followUpCount: 0,
    jobWalkthroughComplete: true,
    recurringServicePitched: false,
  },
  {
    id: 'JOB-0002',
    clientName: 'Donny Dobacke',
    phone: '717-555-0123',
    email: '',
    address: '123 Maple St',
    cityArea: 'Dover',
    description: 'Front beds mulch install',
    jobType: 'Mulch',
    status: 'Follow-Up Needed',
    priority: 'Medium',
    leadSource: 'Referral',
    nextAction: 'Call to follow up on mulch estimate',
    nextActionDate: '2025-12-13',
    scheduledDate: '2025-12-16',
    estRevenue: 500,
    estCost: 200,
    estProfit: 300,
    estMargin: 60,
    paymentStatus: 'Unpaid',
    notes: '',
    followUpCount: 1,
    jobWalkthroughComplete: false,
    recurringServicePitched: false,
  },
  {
    id: 'LEAD-1003',
    clientName: 'Sarah Jenkins',
    phone: '717-555-9876',
    email: 's.jenkins@email.com',
    address: '89 Pine Cone Rd',
    cityArea: 'York',
    description: 'Spring clean up and hedge trimming',
    jobType: 'Maintenance',
    status: 'Lead',
    priority: 'Medium',
    leadSource: 'Google Search',
    lastContactDate: '2025-11-20',
    nextAction: 'Schedule walkthrough',
    nextActionDate: '2025-11-28',
    estRevenue: 450,
    estCost: 150,
    estProfit: 300,
    estMargin: 66,
    followUpCount: 2,
    jobWalkthroughComplete: false,
    recurringServicePitched: true,
    paymentStatus: 'Unpaid',
    notes: 'Requested recurring mowing service quote too.'
  },
  {
    id: 'JOB-0004',
    clientName: 'Heritage Hills HOA',
    phone: '717-555-1111',
    email: 'manager@heritage.com',
    address: '2700 Mt Rose Ave',
    cityArea: 'York',
    description: 'Weekly mowing of common areas',
    jobType: 'Weekly Mow',
    status: 'Scheduled',
    priority: 'Medium',
    leadSource: 'Commercial Contract',
    scheduledDate: '2025-06-01',
    crewLead: 'Mike',
    estRevenue: 450,
    estCost: 150,
    estProfit: 300,
    estMargin: 66,
    paymentStatus: 'Paid',
    notes: 'Gate code 1234',
    followUpCount: 0,
    jobWalkthroughComplete: true,
    recurringServicePitched: true,
  },
  {
    id: 'JOB-0005',
    clientName: 'Robert Smith',
    phone: '717-555-2222',
    email: '',
    address: '1500 Hollywood Dr',
    cityArea: 'York',
    description: 'Weekly residential mow',
    jobType: 'Weekly Mow',
    status: 'Scheduled',
    priority: 'Low',
    leadSource: 'Referral',
    scheduledDate: '2025-06-01',
    estRevenue: 65,
    estCost: 25,
    estProfit: 40,
    estMargin: 61,
    paymentStatus: 'Unpaid',
    notes: '',
    followUpCount: 0,
    jobWalkthroughComplete: true,
    recurringServicePitched: true,
  },
  {
    id: 'JOB-0006',
    clientName: 'The Paddock',
    phone: '717-555-3333',
    email: '',
    address: '3400 Eastern Blvd',
    cityArea: 'York',
    description: 'Commercial perimeter mow',
    jobType: 'Weekly Mow',
    status: 'Scheduled',
    priority: 'Medium',
    leadSource: 'Cold Call',
    scheduledDate: '2025-06-01',
    estRevenue: 120,
    estCost: 40,
    estProfit: 80,
    estMargin: 66,
    paymentStatus: 'Unpaid',
    notes: 'Watch out for cars',
    followUpCount: 0,
    jobWalkthroughComplete: true,
    recurringServicePitched: true,
  }
];

export const mockEstimates: MowEstimate[] = [
  {
    id: 'EST-1001',
    clientName: 'markus Biddle',
    address: '5300 pinchtown rd',
    zip: '17315',
    acreage: 1.6,
    estMins: 106,
    totalHours: 1.77,
    price: 125.00,
    date: '2025-05-20',
    estimator: 'Chad'
  }
];

export const getStats = (jobs: Job[]) => {
  return {
    totalRevenue: jobs.reduce((acc, job) => acc + (job.actualRevenue || job.estRevenue), 0),
    activeJobs: jobs.filter(j => j.status === 'Scheduled' || j.status === 'In Progress').length,
    avgMargin: jobs.length ? (jobs.reduce((acc, job) => acc + job.estMargin, 0) / jobs.length) : 0,
    pendingFollowUps: jobs.filter(j => j.status === 'Follow-Up Needed' || j.status === 'Lead').length,
  };
};
